### PR TITLE
Make Client::findWorkflow() return null when workflow does not exist.

### PR DESCRIPTION
**Pull request by pylebecq**

### CODE REVIEW

**Comment by Ciboulette** [comment]
@pylebecq Just out of curiosity what does the Engine returns when `response->data` is not set ?

**Comment by Ciboulette** [comment]
@pylebecq Ok actually I See. 

The engine send back a 404 request with the following Json {error: "No workflow instance found with the id : {custom_id}}. I need to change this

**Comment by pylebecq** [comment]
@Ciboulette I think it does **not** return a 404 error response code. It would be better if it did.

**Comment by Ciboulette** [comment]
Ok I'm on it. 
Because the way it works today is :
PHP client lib <=> website <=> engine. The engine is answering 404 but not the website.

**Comment by pylebecq** [comment]
@Ciboulette If we make this change I will change the patch to check the HTTP status code instead, which will be much more reliable

**Comment by pylebecq** [comment]
Updated the patch. This PR needs zenaton/core#87 to be deployed.

**Pull request merged**
